name: build-and-test
on: [push, pull_request]
jobs:
  build-on-osx:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install conan
      run: pip install conan
    - name: Install dependencies via conan
      run: conan install -if build conanfile.txt
    - name: Configure
      run: cmake -S . -B build -G Ninja
    # - name: Debug gh-action
    #   run: find generated -type f
    - name: Build
      run: cmake --build build
    - name: Test
      run: cmake --build build --target test

